name: ptig
version: "0.241101"
summary: "Pytigon runtime and devtools"
description: "Pytigon runtime and devtools"
grade: stable
confinement: strict
base: core24
icon: snap/gui/ptig.png

apps:
  ptig:
    command: bin/python3 -m pytigon.ptig
    extensions: [gnome]
    plugs:
      - audio-playback
      - home
      - network
      - network-status
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/:$LD_LIBRARY_PATH:$SNAP/usr/lib/python3/dist-packages"
      "PYTHONPATH": "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

  devtools:
    command: bin/python3 -m pytigon.ptig schdevtools
    extensions: [gnome]
    plugs:
      - audio-playback
      - home
      - network
      - network-status
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/:$LD_LIBRARY_PATH:$SNAP/usr/lib/python3/dist-packages"
      "PYTHONPATH": "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

  demo:
    command: bin/python3 -m pytigon.ptig schpytigondemo
    extensions: [gnome]
    plugs:
      - audio-playback
      - home
      - network
      - network-status
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/:$LD_LIBRARY_PATH:$SNAP/usr/lib/python3/dist-packages"
      "PYTHONPATH": "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

  python:
    command: bin/python3
    extensions: [gnome]
    plugs:
      - audio-playback
      - home
      - network
      - wayland
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/:$LD_LIBRARY_PATH:$SNAP/usr/lib/python3/dist-packages"
      "PYTHONPATH": "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages"

parts:
  ptig-parts1:
    plugin: python
    source: .

    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    python-packages:
      - wheel
      - autobahn
      - reportlab
      - svglib
      - pyopenssl
      - pytigon-gui
      - psycopg2-binary

    stage-packages:
      - python3-wxgtk4.0
      - python3-wxgtk-webview4.0
      - python3-wxgtk-media4.0
      - libpulse0
      - libssl-dev
      - zlib1g
      - libpython3-dev
      - libpython3-stdlib
      - postgresql-client
      - postgresql-client-common
      - libpq-dev
      - libxkbcommon-dev
      - xkb-data
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-image-2.0-0
      - libtbb-dev

  gpu-2404:
    after: [ptig-parts1]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
